// Package router wires every handler into the Gin route tree. It is the one
// place that knows both "which URL" and "which RBAC role" — handlers themselves
// stay unaware of routing/auth concerns.
package router

import (
	"github.com/gin-contrib/gzip"
	"github.com/gin-gonic/gin"
	swaggerfiles "github.com/swaggo/files"
	ginswagger "github.com/swaggo/gin-swagger"

	"github.com/rs/zerolog"

	_ "bookreader/backend/docs" // swagger docs registration (generated by swag init)
	"bookreader/backend/internal/config"
	"bookreader/backend/internal/domain"
	adminh "bookreader/backend/internal/handler/admin"
	publich "bookreader/backend/internal/handler/public"
	"bookreader/backend/internal/middleware"
	"bookreader/backend/internal/service"
	"bookreader/backend/pkg/cache"
	"bookreader/backend/pkg/jwtutil"
)

type Handlers struct {
	Auth      *publich.AuthHandler
	Me        *publich.MeHandler
	Books     *publich.BookHandler
	Favorites *publich.FavoriteHandler
	Bookmarks *publich.BookmarkHandler
	Notes     *publich.NoteHandler
	Search    *publich.SearchHandler

	AdminBooks      *adminh.BookHandler
	AdminFiles      *adminh.FileHandler
	AdminLanguages  *adminh.LanguageHandler
	AdminCategories *adminh.CategoryHandler
	AdminUsers      *adminh.UserHandler
	AdminStats      *adminh.StatsHandler
	AdminAudit      *adminh.AuditHandler
	AdminImport     *adminh.ImportHandler
}

type Services struct {
	Audit *service.AuditService
}

func New(cfg *config.Config, log zerolog.Logger, issuer *jwtutil.Issuer, redisCache *cache.Cache, h *Handlers, svc *Services) *gin.Engine {
	if cfg.Env == "production" {
		gin.SetMode(gin.ReleaseMode)
	}

	r := gin.New()
	r.Use(
		middleware.RequestID(),
		middleware.Recovery(log),
		middleware.RequestLogger(log),
		middleware.SecureHeaders(),
		middleware.CORS(cfg.CORS.AllowedOrigins),
		gzip.Gzip(gzip.DefaultCompression),
		middleware.RateLimit(redisCache, cfg.RateLimit.RequestsPerMinute),
		middleware.CSRF(),
	)

	r.Static("/uploads", cfg.Storage.LocalBaseDir)
	r.GET("/healthz", func(c *gin.Context) { c.JSON(200, gin.H{"status": "ok"}) })
	if cfg.Env != "production" {
		r.GET("/swagger/*any", ginswagger.WrapHandler(swaggerfiles.Handler))
	}

	api := r.Group("/api/v1")
	registerPublicRoutes(api, issuer, h)
	registerAdminRoutes(api, issuer, h, svc)

	return r
}

func registerPublicRoutes(api *gin.RouterGroup, issuer *jwtutil.Issuer, h *Handlers) {
	auth := api.Group("/auth")
	auth.POST("/register", h.Auth.Register)
	auth.POST("/login", h.Auth.Login)
	auth.POST("/refresh", h.Auth.Refresh)
	auth.POST("/logout", h.Auth.Logout)

	api.GET("/me", middleware.Auth(issuer), h.Me.Me)
	api.GET("/me/favorites", middleware.Auth(issuer), h.Favorites.List)

	// NOTE: Gin's router rejects two different wildcard names (:slug vs :id) at the
	// same path depth, so the SEO-friendly slug lookup lives under the static
	// "/by-slug/" prefix; every other /books/:id/... route shares one wildcard name.
	books := api.Group("/books")
	books.GET("", middleware.OptionalAuth(issuer), h.Books.List)
	books.GET("/popular", h.Books.Popular)
	books.GET("/by-slug/:slug", middleware.OptionalAuth(issuer), h.Books.Detail)

	byID := api.Group("/books")
	byID.GET("/:id/chapters", h.Books.Chapters)
	byID.GET("/:id/chapters/:number", h.Books.ChapterContent)
	byID.POST("/:id/favorite", middleware.Auth(issuer), h.Favorites.Add)
	byID.DELETE("/:id/favorite", middleware.Auth(issuer), h.Favorites.Remove)
	byID.GET("/:id/bookmarks", middleware.Auth(issuer), h.Bookmarks.ListByBook)
	byID.GET("/:id/last-position", middleware.Auth(issuer), h.Bookmarks.LastPosition)
	byID.GET("/:id/notes", middleware.Auth(issuer), h.Notes.ListByBook)

	bookmarks := api.Group("/bookmarks")
	bookmarks.Use(middleware.Auth(issuer))
	bookmarks.POST("", h.Bookmarks.Create)
	bookmarks.PUT("/last-position", h.Bookmarks.SaveLastPosition)
	bookmarks.DELETE("/:id", h.Bookmarks.Delete)

	search := api.Group("/search")
	search.GET("/verses", h.Search.SearchVerses)
	search.GET("/books", h.Search.SearchBooks)

	notes := api.Group("/notes")
	notes.Use(middleware.Auth(issuer))
	notes.POST("", h.Notes.Create)
	notes.PUT("/:id", h.Notes.Update)
	notes.DELETE("/:id", h.Notes.Delete)
}

func registerAdminRoutes(api *gin.RouterGroup, issuer *jwtutil.Issuer, h *Handlers, svc *Services) {
	admin := api.Group("/admin")
	admin.Use(middleware.Auth(issuer), middleware.RequireRole(domain.RoleAdmin, domain.RoleEditor))

	admin.GET("/stats", h.AdminStats.Dashboard)
	admin.GET("/audit-logs", middleware.RequireRole(domain.RoleAdmin), h.AdminAudit.List)

	books := admin.Group("/books")
	books.GET("", h.AdminBooks.List)
	books.GET("/:id", h.AdminBooks.Detail)
	books.POST("", middleware.Audit(svc.Audit, "create", "book"), h.AdminBooks.Create)
	books.PUT("/:id", middleware.Audit(svc.Audit, "update", "book"), h.AdminBooks.Update)
	books.DELETE("/:id", middleware.RequireRole(domain.RoleAdmin), middleware.Audit(svc.Audit, "delete", "book"), h.AdminBooks.Delete)
	books.POST("/:id/cover", middleware.Audit(svc.Audit, "upload_cover", "book"), h.AdminFiles.UploadCover)
	books.POST("/:id/pdf", middleware.Audit(svc.Audit, "upload_pdf", "book"), h.AdminFiles.UploadPDF)

	languages := admin.Group("/languages")
	languages.GET("", h.AdminLanguages.List)
	languages.POST("", middleware.Audit(svc.Audit, "create", "language"), h.AdminLanguages.Create)
	languages.PUT("/:id", middleware.Audit(svc.Audit, "update", "language"), h.AdminLanguages.Update)
	languages.DELETE("/:id", middleware.RequireRole(domain.RoleAdmin), middleware.Audit(svc.Audit, "delete", "language"), h.AdminLanguages.Delete)

	categories := admin.Group("/categories")
	categories.GET("", h.AdminCategories.List)
	categories.POST("", middleware.Audit(svc.Audit, "create", "category"), h.AdminCategories.Create)
	categories.PUT("/:id", middleware.Audit(svc.Audit, "update", "category"), h.AdminCategories.Update)
	categories.DELETE("/:id", middleware.RequireRole(domain.RoleAdmin), middleware.Audit(svc.Audit, "delete", "category"), h.AdminCategories.Delete)

	imports := admin.Group("/import")
	imports.GET("", h.AdminImport.List)
	imports.POST("/upload", middleware.Audit(svc.Audit, "upload", "import"), h.AdminImport.Upload)
	imports.GET("/:id", h.AdminImport.Status)
	imports.GET("/:id/stream", h.AdminImport.Stream)
	imports.POST("/:id/commit", middleware.Audit(svc.Audit, "commit", "import"), h.AdminImport.Commit)

	users := admin.Group("/users")
	users.Use(middleware.RequireRole(domain.RoleAdmin))
	users.GET("", h.AdminUsers.List)
	users.PUT("/:id/role", middleware.Audit(svc.Audit, "change_role", "user"), h.AdminUsers.ChangeRole)
	users.DELETE("/:id", middleware.Audit(svc.Audit, "deactivate", "user"), h.AdminUsers.Deactivate)
}
